### PR TITLE
Ita_Industries from Mapper for all Trade Leads endpoints

### PR DESCRIPTION
**Pull request by tmhammer**

### CODE REVIEW

**Comment by tmhammer** [comment]
https://www.pivotaltracker.com/story/show/105665602

**Comment by calumhalcrow** [comment]
@tmhammer is it possible to deal with the codeclimate issues?

**Comment by calumhalcrow** [comment]
@tmhammer also: rubocop -a and rebase onto master please :-)

**Comment by calumhalcrow** [comment]
One thought @tmhammer: since all trade lead importers now pull data from IM, should you remove `include VersionableResource` from them all? If it remains, if the taxonomy changes but the source doesn't, the endpoint will not be updated on import.

**Comment by tmhammer** [comment]
Thanks for pointing that out @calumhalcrow, I ended up tweaking the Versionable logic slightly so we can make an importer still import even if the source doesn't change.  Which means we can keep using the versionable metadata on the endpoints.

**Comment by calumhalcrow** [comment]
ok looks good.

**Pull request closed without merging**
