### PR TITLE
Envirotech import refactoring

### PR DESCRIPTION
**Pull request by baraabourghli**

### CODE REVIEW

**Comment by baraabourghli** [comment]
this should be more straightforward to maintain. what do you say @calumhalcrow ?

**Comment by calumhalcrow** [comment]
@baraabourghli yeah, this is the better approach. Thanks for implementing it.

Regarding `Array#uniq_push!`: I believe there's a way in which you can achieve the same effect but without monkey patching Array (it's better to avoid monkey patching core classes if possible). You can use Array unions (single pipe `|`):

`issue[:regulation_ids] |= [regulation[:source_id]]`

Can you back out the monkey patch and use this approach instead?

**Comment by baraabourghli** [comment]
Okay, i agree :+1:

**Comment by baraabourghli** [comment]
BTW @calumhalcrow it is done, i forgot to mention it : P

**Comment by calumhalcrow** [comment]
Oh ok, thanks for pointing that out :-) will review shortly...

**Pull request merged**
