### PR TITLE
Add user authentication for V2

### PR DESCRIPTION
**Pull request by calumhalcrow**
[#86679256]

### CODE REVIEW

**Comment by calumhalcrow** [comment]
@jamesisaacs I've opened this so that you can have a look over it at your leisure. It isn't fully finished yet, but it will be very soon, at which time I'd be asking you to review anyway (so you might as well have it now ;-) ).

**Comment by calumhalcrow** [comment]
@jamesisaacs sorry that this is such a beast. But I feel it's ready to be merged now (I don't intend to add more changes unless of course to fix bugs etc.).

**Comment by jamesisaacs** [comment]
There's a small typo in README.md:
     
     `bundle install mailcatcher` should be `gem install mailcatcher`.

**Comment by calumhalcrow** [comment]
README fixed.

**Pull request merged**
