### PR TITLE
[#117849123] Market intelligence and FAQs update

### PR DESCRIPTION
**Pull request by tmhammer**

### CODE REVIEW

**Comment by tmhammer** [comment]
I think this should be good to go @davidpranata, I can put this on staging once the cookbooks PR is merged and deployed.

**Comment by tmhammer** [comment]
@davidpranata, changed `public_url` to `url`

**Comment by davidpranata** [comment]
@tmhammer In [`salesforce/mappable.rb`](https://github.com/GovWizely/webservices/blob/830e09977bf7031355fd2cfe7f59519bdc50df4a/app/models/salesforce_article/mappable.rb#L31), `answer` and `question` are actually `title` and `atom`.

In FAQ, `answer` and `question` are populated.
For other Salesforce article types, `title` and `atom` are populated.

Have you considered using `title` and `atom` for all Salesforce article types including `FAQ`?
You will not need to redefine `FIELD_MAPPINGS` in `salesforce_article/faq_data.rb` and `MULTI_FIELDS` in `salesforce_article/query.rb`.
The [Code Climate duplication warnings](https://codeclimate.com/github/GovWizely/webservices/compare/tim/market-intelligence) will also disappear.

In the faq [`_entries.json.jbuilder`](https://github.com/GovWizely/webservices/blob/830e09977bf7031355fd2cfe7f59519bdc50df4a/app/views/api/v2/salesforce_articles/faq/_entries.json.jbuilder), you can render `question` with `title` and `answer` with `atom`.
```ruby
  ...
  json.id entry[:id]
  json.question entry[:title]
  json.answer entry[:atom]
  ...
```

**Comment by tmhammer** [comment]
Thanks for that suggestion @davidpranata, it does make the code cleaner.  I have made those changes and rebased.

**Pull request merged**
