### PR TITLE
Spec data reorg

### PR DESCRIPTION
**Pull request by calumhalcrow**

### CODE REVIEW

**Comment by calumhalcrow** [comment]
@baraabourghli looks ok. The approach is:
- only have _input_ (i.e. source) files in /spec/fixtures
- all other data files should be as close to the relevant spec as possible (in the same dir or in a child dir with the same name).

**Comment by baraabourghli** [comment]
@calumhalcrow BTW, I wanted to do specs per source, but I was worried about making huge changes per commit and missing some details. Anyway, I can rewrite the commits history and organize changes per source if you think it is better to have?

**Comment by baraabourghli** [comment]
@calumhalcrow I think it is ready to be reviewed.

**Comment by calumhalcrow** [comment]
@baraabourghli I don't think it matters about how the changes are chopped up into commits. This looks good. I'll do some local testing, then merge and deploy to staging.

**Pull request merged**
