### PR TITLE
Update Taxonomy endpoint

### PR DESCRIPTION
**Pull request by tmhammer**

### CODE REVIEW

**Comment by tmhammer** [comment]
https://www.pivotaltracker.com/story/show/114726519

**Comment by calumhalcrow** [comment]
@tmhammer you added a binary file called data/webprotege.zip. It doesn't appear to be used by the changes. Did you mean to include this?

**Comment by calumhalcrow** [comment]
I'm going to defer the review of this to @viclim as the changes will ultimately be consumed by his work on MI.

**Comment by tmhammer** [comment]
@viclim  You can merge this as soon as you'd like, probably the sooner the better.  I'm working on a new story since the query expansion requirements have been updated:  https://www.pivotaltracker.com/story/show/115885023.  The work for this new story is in a new branch that's based on this one, so this still needs to be merged.

**Pull request merged**
